1gty
katushka419/fyoylflio- pull request #1
Opened 2022-02-18 20:47 UTC by katushka419

2022-02-21 07:45 UTC, merged

2022-02-21 07:46 UTC, katushka419 commented
.

2022-02-21 07:47 UTC, katushka419 reviewed
@dmitrii-kruglov

2022-02-21 19:59 UTC, dmitrii-kruglov requested changes
Заменить операторы ввода/вывода. Выделить решение в первой задаче в отдельную функцию. Во второй поправить выравнивание

2022-02-21 19:59 UTC, dmitrii-kruglov commented on README.md
> +     printf ("Исходные данные: \n");
Мы проходим другие операции ввода и вывода, давайте будем использовать материал из семинаров и лекций

2022-02-21 19:59 UTC, dmitrii-kruglov commented on README.md
> +     s=a* b;
BP: s = a * b;

2022-02-21 19:59 UTC, dmitrii-kruglov commented on README.md
> +     s=a* b;
Решение необходимо выделить в отдельную функцию

2022-02-21 19:59 UTC, dmitrii-kruglov commented on р
> +return a * 2.54;
Следите, пожалуйста, за выравниванием

2022-03-11 05:32 UTC, dmitrii-kruglov commented
@katushka419 тут были комментарии